# # delta dhemes
# [".delta"]
#     type = "git-repo"
#     url = "https://github.com/dandavison/delta.git"
#     refreshPeriod = "168h"

# [".oh-my-zsh"]
#     type = "git-repo"
#     url = "https://github.com/ohmyzsh/ohmyzsh.git"
#     refreshPeriod = "168h"
