[settings]
cargo.binstall = false

[tools]
"cargo:bottom" = "latest"
"cargo:ck-search" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"go:github.com/wagoodman/dive" = "latest"
go = "latest"
node = "latest"
pi = "latest"
python = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
uv = "latest"
